name: Trigger auto deployment for fe072654eastus

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ sc-eastus-072654 ]
    paths:
    - '**'
    - '.github/workflows/fe072654eastus-AutoDeployTrigger-e45c9f2b-e05a-4019-bb8e-3a337278928b.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FE072654EASTUS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.FE072654EASTUS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FE072654EASTUS_REGISTRY_PASSWORD }}
          containerAppName: fe072654eastus
          resourceGroup: nonvnet-nonlong-eastus20230401p-202307280024-rg
          imageToBuild: snehaparacr.azurecr.io/fe072654eastus:${{ github.sha }}
          

     

