name: Trigger auto deployment for fe211533eastus

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ sc-eastus-211533 ]
    paths:
    - '**'
    - '.github/workflows/fe211533eastus-AutoDeployTrigger-34b180f2-9748-4fab-9c12-180b9f4be694.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FE211533EASTUS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.FE211533EASTUS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FE211533EASTUS_REGISTRY_PASSWORD }}
          containerAppName: fe211533eastus
          resourceGroup: nonvnet-nonlong-eastus-202306011413-rg
          imageToBuild: snehaparacr.azurecr.io/fe211533eastus:${{ github.sha }}
          

     

